# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "categories", :force => true do |t|
    t.column "name",        :string
    t.column "image",       :binary
    t.column "description", :string
  end

  create_table "categories_webaddresses", :id => false, :force => true do |t|
    t.column "category_id",   :integer
    t.column "webaddress_id", :integer
  end

  add_index "categories_webaddresses", ["category_id", "webaddress_id"], :name => "index_categories_webaddresses_on_category_id_and_webaddress_id", :unique => true
  add_index "categories_webaddresses", ["webaddress_id"], :name => "index_categories_webaddresses_on_webaddress_id"

  create_table "hosts", :force => true do |t|
    t.column "hostname",        :string
    t.column "username",        :string
    t.column "password",        :string
    t.column "enable_password", :string
    t.column "dirty",           :boolean
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "admin",           :boolean
    t.column "enabled",         :boolean, :default => true
    t.column "can_deploy",      :boolean, :default => true
  end

  create_table "webaddresses", :force => true do |t|
    t.column "site",       :string
    t.column "path",       :string
    t.column "reason",     :string
    t.column "ticket",     :string
    t.column "user_id",    :integer,  :null => false
    t.column "created_at", :datetime
  end

end
